baseURL = 'https://kaleidooa.github.io/'
languageCode = 'ko-kr'
title = '여정의 기록'
theme = 'PaperMod'

[params]
  env = 'production'
  description = 'Problem Solver & Developer'
  author = '내 이름'
  # GitHub, Email 등의 아이콘 링크
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/내깃허브아이디"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:내이메일@gmail.com"

# ✨ LaTeX(MathJax) 수식 지원을 위한 설정
[params.math]
  enable = true